name: event_management_app
description: "A new Flutter project for managing events."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Existing dependencies
  cupertino_icons: ^1.0.8

  # Additional dependencies for the app
  provider: ^6.0.5 # For state management
  http: ^1.0.0 # For API requests
  hive: ^2.2.3 # For local storage
  qr_flutter: ^4.0.0 # For QR code generation
  flutter_barcode_scanner: ^2.0.0 # For QR code scanning
  table_calendar: ^3.0.0 # For calendar display
  flutter_local_notifications: ^18.0.1 # For reminders and alerts
  shared_preferences: ^2.1.0 # For simple data storage
  firebase_core: ^3.11.0 # Updated to the latest stable version
  firebase_auth: ^5.4.2 # Updated to the latest stable version
  cloud_firestore: ^5.6.3 # Updated to the latest stable version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Updated to the latest stable version

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - assets/images/
    - assets/icons/
